apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      version: v1           # Pod label to be used by Service to select the pods from this deployment
  replicas: 3                # number of replica of the Pods
  template:
    metadata:
      labels:
        env: dev         # Pod's label
        app: backend
        version: v1
    spec:
      containers:
      - name: backend-container
        image: sebasnates/job-tracker-backend      # which image it will use
        ports:
        - containerPort: 8080    # Port exposed by container inside the Pod

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    version: v1       # label of the service
spec:
  type: ClusterIP
  ports:
  - port: 8080            # the port on which the service is listening
    protocol: TCP
    targetPort: 8080      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  selector:
    version: v1       # Pod label that service is using to select Pods
