# Generated by Django 5.1 on 2024-08-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_remove_jobposition_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobposition",
            name="job_description",
        ),
        migrations.AddField(
            model_name="jobposition",
            name="description",
            field=models.TextField(default="description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobposition",
            name="keywords",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="JobDescription",
        ),
    ]
