name: Deploy to AWS EKS

on:
  push:
    branches:
      - dev
    paths:
      - "helm-backend/**"
      - "helm-frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup kubectl
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name job-tracker-cluster

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Deploy Backend with Helm
        run: |
          helm upgrade --install backend helm-backend --namespace backend --create-namespace

      - name: Deploy Frontend with Helm
        run: |
          helm upgrade --install frontend helm-frontend --namespace frontend --create-namespace
